name: Change GitHub Notifications Status

on:
  schedule:
    - cron: '3 * * * *'     # 毎時実行（UTC）
  workflow_dispatch:        # 手動実行も可能

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Setup dependencies
      - name: Sync dependencies
        run: uv sync

      # Run python script to change notifications status
      - name: Change Notifications Status
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          uv run change_notifications_status.py
